"""add_is_protected_to_channels

Revision ID: e28b3802911e
Revises: 57cbe15f57df
Create Date: 2026-06-28 16:53:22.970845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e28b3802911e'
down_revision: Union[str, Sequence[str], None] = '57cbe15f57df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('is_protected', sa.Boolean(), nullable=True))
    op.drop_constraint(None, 'epg_data', type_='foreignkey')
    op.create_foreign_key(None, 'epg_data', 'epg_sources', ['source_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'epg_data', type_='foreignkey')
    op.create_foreign_key(None, 'epg_data', 'epg_sources', ['source_id'], ['id'])
    op.drop_column('channels', 'is_protected')
    # ### end Alembic commands ###
