"""init and add auto scan fields

Revision ID: fe2f4b80f2a9
Revises: 
Create Date: 2026-04-25 09:41:13.394488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe2f4b80f2a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('epg_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'epg_sources', ['source_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('playlist_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auto_scan_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('auto_scan_interval', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_auto_scan_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playlist_profiles', schema=None) as batch_op:
        batch_op.drop_column('last_auto_scan_at')
        batch_op.drop_column('auto_scan_interval')
        batch_op.drop_column('auto_scan_enabled')

    with op.batch_alter_table('epg_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'epg_sources', ['source_id'], ['id'])

    # ### end Alembic commands ###
